name: Verify Container Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install pip dependencies
      working-directory: builder
      run: pip install -r requirements.txt

    - name: Run builder script
      working-directory: builder
      run: python3 main.py
